#!/bin/bash
repos_path=$(git rev-parse --show-toplevel)

read -p "Are you sure you want to remove all branches (local and remote) that are merged into origin/master? [y/N] "

if [[ ! $REPLY =~ ^[Yy]$ ]]; then
  exit 1
fi

for merged_branch in $(git branch -a --merged origin/master | grep -v master); do
  if echo $merged_branch | grep -E "^remotes/origin" > /dev/null 2>&1; then
    branch_name=$(basename "${merged_branch}")
    git push origin ":${branch_name}"
    git branch -dr "origin/${branch_name}"
  else
    git branch -d "${branch_name}"
  fi
done